name: ttcm_flutter_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  just_audio: ^0.9.37
  logger: ^2.2.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true

  generate: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
